name: Deploy Roulotte

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Create Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Deployment
        uses: peter-evans/create-deployment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          ref: ${{ github.ref }}
          auto_merge: false
          transient_environment: false
          production_environment: true

      - name: Set Deployment Status
        uses: peter-evans/create-deployment-status@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          state: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
